// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUHoshBVTTw1m41avAU45eO5Yxp0l_LqM',
    appId: '1:601852945376:web:ddbe6f50adfb90bcc74185',
    messagingSenderId: '601852945376',
    projectId: 'workout-tracker-a368c',
    authDomain: 'workout-tracker-a368c.firebaseapp.com',
    storageBucket: 'workout-tracker-a368c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSBaGpJrqpHD0uWEr4QGh1al7ptvi7tyA',
    appId: '1:601852945376:android:3595216742452cc0c74185',
    messagingSenderId: '601852945376',
    projectId: 'workout-tracker-a368c',
    storageBucket: 'workout-tracker-a368c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcfSpY3p-78RdJKIlBBrvRbZTsZJOGe6M',
    appId: '1:601852945376:ios:c30c21db7551130bc74185',
    messagingSenderId: '601852945376',
    projectId: 'workout-tracker-a368c',
    storageBucket: 'workout-tracker-a368c.appspot.com',
    iosBundleId: 'com.seonho.workoutTracker',
  );

}